### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/NEd2#1]
Error:  
```bash 
gavr@arch ~/P/NEd2 (main) [1]> nim r --hints=off --threads:on ned.nim
/home/gavr/Projects/NEd2/ned.nim(128, 39) Warning: implicit conversion to 'cstring' from a non-const location: w.filePath; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(156, 28) Warning: implicit conversion to 'cstring' from a non-const location: $i; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(164, 27) Warning: implicit conversion to 'cstring' from a non-const location: filename; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(227, 25) Warning: implicit conversion to 'cstring' from a non-const location: $id; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(322, 26) Warning: implicit conversion to 'cstring' from a non-const location: $e.id; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(325, 27) Warning: implicit conversion to 'cstring' from a non-const location: e.gs; this will become a compile time error in the future [CStringConv]
/home/gavr/Projects/NEd2/ned.nim(370, 14) Error: undeclared identifier: 'newPopoverMenuFromModel'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 4): 'newPopoverMenuBarFromModel' [proc declared in /home/gavr/.nimble/pkgs/gintro-#head/gintro/gtk4.nim(9739, 6)]
 (3, 4): 'newPopoverMenuBarFromModel' [proc declared in /home/gavr/.nimble/pkgs/gintro-#head/gintro/gtk4.nim(9755, 6)]
 ```

**Comment by gavr123456789** [comment]
maybe the code was written when GTK was version 3.98 and something changed

**Comment by StefanSalewski** [comment]
Yes, that code was written early in 2021, and was mainly a GTK4 and GtkSourceView5 test. Indeed I intended to continue working on this editor, but GtkSourceView and GtkTextView, its foundation, is not easy. Unfortunately I do not really understand the initial NEd app any more, which was written in late 2015 with the oldgtk3 module.

Please tell me exactly what the error is and how I can fix it. Should be not that difficult for you (Hint: we generally use overloading for function names, so what do you think about the name newPopoverMenuBarFromModel ?)

**Comment by StefanSalewski** [comment]
And note that NEd2 is not amongst the 6 pinned Apps that github permanently shows, but deeply hidden. And from the README we have: "This is the start of a port of the NEd Nim GTK3 editor to GTK4." So we really should not expect that it is a useful tool already and all the tiny issues get permanently fixed.

**Comment by StefanSalewski** [comment]
Fixed.

Note that you have to install the two files shipped with the old GTK3 Ned for syntax highlighting and color scheme properly to get it working. File system paths of these files is always a daunting task. And you have to compile with option --threads:on

**Comment by gavr123456789** [comment]
Nice, able to build now. It remains to figure out the code highlighting
![image](https://user-images.githubusercontent.com/30507409/141677419-eef51af3-1ec5-41fa-90b0-a17f8a003dbb.png)

**Comment by StefanSalewski** [comment]
For me it works, even nimsuggest with CTRL E.

I guess my path to the two files is currently

$ tree .local/share/gtksourceview-5/
.local/share/gtksourceview-5/
├── language-specs
│   └── nim.lang
└── styles
    └── nimdark1.xml

The files are from old Ned at github. I have used other locations before, but there the files get lost by doing updates. In above path they survived.
